# pipelines to push agent container inside agent folder to dockerhub with docker token

name: push

on:
  push:
    branches:
      - master

jobs:
  build-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build agent -t jeffreyhutchens/agent:${{ github.sha }}
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push jeffreyhutchens/agent:${{ github.sha }}

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build api -t jeffreyhutchens/api:${{ github.sha }}
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push jeffreyhutchens/api:${{ github.sha }}

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build front -t jeffreyhutchens/front:${{ github.sha }}
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push jeffreyhutchens/front:${{ github.sha }}